/*
-- Query: select *
from abrordob_markers
LIMIT 0, 1000

-- Date: 2024-11-04 18:37
*/
INSERT INTO `` (`marker_id`,`colour`,`latitude`,`longitude`,`text`,`date_time`) VALUES ('alex-dolomites','blue',46.648266,11.689302,'Shout out to the gaffa @⁨יוני⁩ for giving me my European sabbatical 👌👌\n\nHas been a long few seasons for me and a chance to rest these weary legs\n\nCurrently scouting out potential venues for future away fixtures and think I\'ve found a beaut right here\n\nWord is spreading across the Italian alps and the latest is that Palamara just didn\'t want it 🤷‍♂️🤷‍♂️','2024-08-11 16:37:00');
INSERT INTO `` (`marker_id`,`colour`,`latitude`,`longitude`,`text`,`date_time`) VALUES ('alex-napoli','blue',40.84111,14.246167,'As this momentus fixture approaches fate has brought 2 titans of football together on a global stage\n\nGod speed to all those playing tonight\n\nORDOB 🟥 🤝 🇦🇷Maradona','2024-05-30 15:04:00');
INSERT INTO `` (`marker_id`,`colour`,`latitude`,`longitude`,`text`,`date_time`) VALUES ('oli-india','red',27.173891,78.04207,'With the aim of providing some inspiration for tomorrow, here’s a photo of one of humanity’s most beautiful creations, being worn by me, with the Taj Mahal in the background','2024-03-27 12:02:00');
INSERT INTO `` (`marker_id`,`colour`,`latitude`,`longitude`,`text`,`date_time`) VALUES ('robin-brazil','purple',-22.949623,-43.20448,'Boys, it\'s the last of my telegrams on my scouting mission across the Americas. Unfortunately, I\'ve found no-one with enough touch, charm and manners to even get a trial for our club. So the message for tonight from Christ the Redeemer in Rio is to play with freedom. Let the Seleção of our Thursday Castlehaven lineup take The Camden Kings by storm. Releasing our inner samba is as simple as rocking step combinations, rolling hip action, and pulsing movements whilst playing tika taka in syncopation. Look for the beautiful ball and play with your instincts, the favelas are with you 🎨🔫 #UDCDB🇧🇷 Um dia comum do barclays!','2024-08-01 16:02:00');
INSERT INTO `` (`marker_id`,`colour`,`latitude`,`longitude`,`text`,`date_time`) VALUES ('robin-cusco','purple',-13.529427,-71.98498,'I couldn\'t convince the good people of Cusco to live watch www.fixturesandresults after they saw our recent season finish. But the alpaca community are all for it.','2024-07-18 19:15:00');
INSERT INTO `` (`marker_id`,`colour`,`latitude`,`longitude`,`text`,`date_time`) VALUES ('robin-mexico','purple',20.682985,-88.56865,'Ahead of tonight\'s big fixture against The Playmakers, there is an important message from the Mayan people of Mexico. They are chanelling the skill & spirit from their native sport Pok-A-Tok, towards our reduced team tonight. And pray that the brick shithouse stands as firm as the stone temples of Chichén Itzá behind me, one the 7 modern wonders of the world. With a win tonight, they claim to honour ORDOB as their 8th wonder. In Pok-A-Tok, the captain of the winning team is beheaded for eternal sanctity. Ka xi’ik teech utsil (good luck) my friends, and Yoni 🙏🇲🇽','2024-07-04 16:59:00');
INSERT INTO `` (`marker_id`,`colour`,`latitude`,`longitude`,`text`,`date_time`) VALUES ('robin-rainbow','purple',-13.870228,-71.30295,'Hola from Peru! My ORDOB shirt moaned at the prospect of going to Machu Picchu with me yesterday. \"Not another bloody world wonder\" it said. To kick off the new season, it instead persisted on joining me on a trek to the nutty altitude of Rainbow mountain sitting at 5,020m. Never forget, that ORDOB belong at the top 🏆','2024-07-18 19:14:00');
INSERT INTO `` (`marker_id`,`colour`,`latitude`,`longitude`,`text`,`date_time`) VALUES ('tim-japan','green',34.967518,135.77971,'I spent an afternoon a couple of weeks back having to CORRECT every tour guide in my sight on what this great shrine actually stands for. Some of them had some absolutely laughable takes. Some stuff about a god of rice? \n\n        Anyway... As any of us would, I launched into countless monologues about it\'s real historic standing. \n\nThe Fushimi Inari Shrine has a red arch for each time a significant moment has happened for ORDOB\'s 5 a side team in history.\n\nFrom John Walters first goal over a year ago, Mitch Gordon\'s last minute winner vs Palamara Jagon, Rob scoring 7 goals in one match, Joe having a beer and a Pad Thai before our first ever game and Mitch missing tonight because of JetLag.\n\nTHIS IS WHY THESE BEAUTIFUL RED ARCHES EXIST\n\nLets add another arch to make it 10,001 tonight ⛩️\n\nCOYORDOB 🦏3️⃣👃','2024-10-17 18:34:00');
INSERT INTO `` (`marker_id`,`colour`,`latitude`,`longitude`,`text`,`date_time`) VALUES ('yoni-colosseum','black',41.89025,12.492373,'When I was here last week, I asked an old, bearded Englishman who was holding a video camera to take my photo. He looked like he knew what he was doing. He asked me what that beautiful shirt I was wearing was, and said how rare it is for such ancient beauty to be eclipsed, upstaged, by a simple piece of clothing. I told him about our history, our philosophy, our aura, our titanic league title. Awestruck, he promised that if we won our next game against Millstone FC, he would change the name of his upcoming sequel to Gladiatordob II, forever linking this collosal amphitheatre of sport and sacrifice with us, the heroes of today.\n\nGo well tonight, lads ⚔','2024-06-27 09:10:00');
INSERT INTO `` (`marker_id`,`colour`,`latitude`,`longitude`,`text`,`date_time`) VALUES ('yoni-vegas','black',36.13524,-115.170845,'Will post the team graphic later as I\'ve just landed at Heathrow, after a week in Las Vegas where some claim resides the World\'s Largest Gentlemen\'s Club. Well, that was until I walked in with the shirt of a gentlemen\'s club far more massive. One of the dancers told me that she\'s seen thousands of strips in her time, but none more beautiful or erotic than the one adorning my torso. She asked if I wanted a dance and I said, \"No, but a word of advice. Put your money on red tonight.\"','2024-08-29 15:06:00');
