"""first commit

Revision ID: a2bfb8bc9128
Revises: 
Create Date: 2024-11-09 18:52:41.492540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2bfb8bc9128'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abrordob_markers',
    sa.Column('marker_id', sa.String(length=20), nullable=False),
    sa.Column('colour', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('text', sa.String(length=16383), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('marker_id'),
    mysql_engine='InnoDB'
    )
    op.create_table('clubs',
    sa.Column('club_id', sa.Uuid(), nullable=False),
    sa.Column('club_name', sa.String(length=50), nullable=False),
    sa.Column('data_source_club_id', sa.String(length=50), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('club_id'),
    mysql_engine='InnoDB'
    )
    op.create_table('data_sources',
    sa.Column('data_source_id', sa.Enum('FOOTBALL_ASSOCIATION', 'MANUAL', name='datasource'), nullable=False),
    sa.Column('data_source_name', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('data_source_id'),
    mysql_engine='InnoDB'
    )
    op.create_table('sports',
    sa.Column('sport_id', sa.Enum('FOOTBALL', name='sport'), nullable=False),
    sa.Column('sport_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('sport_id'),
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=130), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_engine='InnoDB'
    )
    op.create_table('club_admins',
    sa.Column('club_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.club_id'], name='fk_clubs_club_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='fk_users_user_id'),
    sa.PrimaryKeyConstraint('club_id', 'user_id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_club_admins_club_id'), 'club_admins', ['club_id'], unique=False)
    op.create_index(op.f('ix_club_admins_user_id'), 'club_admins', ['user_id'], unique=False)
    op.create_table('leagues',
    sa.Column('league_id', sa.Uuid(), nullable=False),
    sa.Column('league_name', sa.String(length=100), nullable=False),
    sa.Column('data_source_league_id', sa.String(length=50), nullable=False),
    sa.Column('data_source_id', sa.Enum('FOOTBALL_ASSOCIATION', 'MANUAL', name='datasource'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.data_source_id'], name='fk_data_sources_data_source_id'),
    sa.PrimaryKeyConstraint('league_id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_leagues_data_source_id'), 'leagues', ['data_source_id'], unique=False)
    op.create_table('metrics',
    sa.Column('metric_id', sa.Uuid(), nullable=False),
    sa.Column('data_source_id', sa.Enum('FOOTBALL_ASSOCIATION', 'MANUAL', name='datasource'), nullable=False),
    sa.Column('metric_name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.data_source_id'], name='fk_data_sources_data_source_id'),
    sa.PrimaryKeyConstraint('metric_id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_metrics_data_source_id'), 'metrics', ['data_source_id'], unique=False)
    op.create_table('players',
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('club_id', sa.Uuid(), nullable=False),
    sa.Column('data_source_player_name', sa.String(length=100), nullable=False),
    sa.Column('better_player_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.club_id'], name='fk_clubs_club_id'),
    sa.PrimaryKeyConstraint('player_id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_players_club_id'), 'players', ['club_id'], unique=False)
    op.create_table('seasons',
    sa.Column('season_id', sa.Uuid(), nullable=False),
    sa.Column('season_name', sa.String(length=50), nullable=False),
    sa.Column('data_source_season_id', sa.String(length=50), nullable=False),
    sa.Column('data_source_id', sa.Enum('FOOTBALL_ASSOCIATION', 'MANUAL', name='datasource'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.data_source_id'], name='fk_data_sources_data_source_id'),
    sa.PrimaryKeyConstraint('season_id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_seasons_data_source_id'), 'seasons', ['data_source_id'], unique=False)
    op.create_table('teams',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('club_id', sa.Uuid(), nullable=False),
    sa.Column('sport_id', sa.Enum('FOOTBALL', name='sport'), nullable=False),
    sa.Column('data_source_team_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.club_id'], name='fk_clubs_club_id'),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.sport_id'], name='fk_sports_sport_id'),
    sa.PrimaryKeyConstraint('team_id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_teams_club_id'), 'teams', ['club_id'], unique=False)
    op.create_index(op.f('ix_teams_sport_id'), 'teams', ['sport_id'], unique=False)
    op.create_table('league_seasons',
    sa.Column('league_id', sa.Uuid(), nullable=False),
    sa.Column('data_source_league_season_id', sa.String(length=50), nullable=False),
    sa.Column('data_source_season_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], name='fk_leagues_league_id'),
    sa.PrimaryKeyConstraint('league_id', 'data_source_league_season_id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_league_seasons_league_id'), 'league_seasons', ['league_id'], unique=False)
    op.create_table('team_leagues',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('league_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], name='fk_leagues_league_id'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], name='fk_teams_team_id'),
    sa.PrimaryKeyConstraint('team_id', 'league_id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_team_leagues_league_id'), 'team_leagues', ['league_id'], unique=False)
    op.create_index(op.f('ix_team_leagues_team_id'), 'team_leagues', ['team_id'], unique=False)
    op.create_table('team_names',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('team_name', sa.String(length=50), nullable=False),
    sa.Column('is_default_name', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], name='fk_teams_team_id'),
    sa.PrimaryKeyConstraint('team_id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_team_names_team_id'), 'team_names', ['team_id'], unique=False)
    op.create_table('team_seasons',
    sa.Column('team_season_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('season_id', sa.Uuid(), nullable=False),
    sa.Column('data_source_id', sa.Enum('FOOTBALL_ASSOCIATION', 'MANUAL', name='datasource'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.data_source_id'], name='fk_data_sources_data_source_id'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], name='fk_seasons_season_id'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], name='fk_teams_team_id'),
    sa.PrimaryKeyConstraint('team_season_id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_team_seasons_data_source_id'), 'team_seasons', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_team_seasons_season_id'), 'team_seasons', ['season_id'], unique=False)
    op.create_index(op.f('ix_team_seasons_team_id'), 'team_seasons', ['team_id'], unique=False)
    op.create_table('competitions',
    sa.Column('competition_id', sa.Uuid(), nullable=False),
    sa.Column('data_source_competition_id', sa.String(length=100), nullable=False),
    sa.Column('competition_name', sa.String(length=100), nullable=False),
    sa.Column('team_season_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['team_season_id'], ['team_seasons.team_season_id'], name='fk_team_seasons_team_season_id'),
    sa.PrimaryKeyConstraint('competition_id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_competitions_team_season_id'), 'competitions', ['team_season_id'], unique=False)
    op.create_table('matches',
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('competition_id', sa.Uuid(), nullable=False),
    sa.Column('goals_for', sa.Integer(), nullable=False),
    sa.Column('goals_against', sa.Integer(), nullable=False),
    sa.Column('goal_difference', sa.Integer(), nullable=False),
    sa.Column('opposition_team_name', sa.String(length=100), nullable=False),
    sa.Column('result', sa.String(length=1), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('home_away_neutral', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.competition_id'], name='fk_competitions_competition_id'),
    sa.PrimaryKeyConstraint('match_id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_matches_competition_id'), 'matches', ['competition_id'], unique=False)
    op.create_table('player_match_performances',
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('metric_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], name='fk_matches_match_id'),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.metric_id'], name='fk_metrics_metric_id'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], name='fk_players_player_id'),
    sa.PrimaryKeyConstraint('player_id', 'match_id', 'metric_id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_player_match_performances_match_id'), 'player_match_performances', ['match_id'], unique=False)
    op.create_index(op.f('ix_player_match_performances_metric_id'), 'player_match_performances', ['metric_id'], unique=False)
    op.create_index(op.f('ix_player_match_performances_player_id'), 'player_match_performances', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_match_performances_player_id'), table_name='player_match_performances')
    op.drop_index(op.f('ix_player_match_performances_metric_id'), table_name='player_match_performances')
    op.drop_index(op.f('ix_player_match_performances_match_id'), table_name='player_match_performances')
    op.drop_table('player_match_performances')
    op.drop_index(op.f('ix_matches_competition_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_competitions_team_season_id'), table_name='competitions')
    op.drop_table('competitions')
    op.drop_index(op.f('ix_team_seasons_team_id'), table_name='team_seasons')
    op.drop_index(op.f('ix_team_seasons_season_id'), table_name='team_seasons')
    op.drop_index(op.f('ix_team_seasons_data_source_id'), table_name='team_seasons')
    op.drop_table('team_seasons')
    op.drop_index(op.f('ix_team_names_team_id'), table_name='team_names')
    op.drop_table('team_names')
    op.drop_index(op.f('ix_team_leagues_team_id'), table_name='team_leagues')
    op.drop_index(op.f('ix_team_leagues_league_id'), table_name='team_leagues')
    op.drop_table('team_leagues')
    op.drop_index(op.f('ix_league_seasons_league_id'), table_name='league_seasons')
    op.drop_table('league_seasons')
    op.drop_index(op.f('ix_teams_sport_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_club_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_seasons_data_source_id'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_players_club_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_metrics_data_source_id'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_leagues_data_source_id'), table_name='leagues')
    op.drop_table('leagues')
    op.drop_index(op.f('ix_club_admins_user_id'), table_name='club_admins')
    op.drop_index(op.f('ix_club_admins_club_id'), table_name='club_admins')
    op.drop_table('club_admins')
    op.drop_table('users')
    op.drop_table('sports')
    op.drop_table('data_sources')
    op.drop_table('clubs')
    op.drop_table('abrordob_markers')
    # ### end Alembic commands ###
