"""test

Revision ID: b9dbb4db42ad
Revises: 2571a69e3101
Create Date: 2024-11-04 20:05:18.869330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9dbb4db42ad'
down_revision: Union[str, None] = '2571a69e3101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_clubs_club_id', 'club_admins', type_='foreignkey')
    op.drop_constraint('fk_users_user_id', 'club_admins', type_='foreignkey')
    op.create_foreign_key('fk_users_user_id', 'club_admins', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key('fk_clubs_club_id', 'club_admins', 'clubs', ['club_id'], ['club_id'])
    op.drop_constraint('fk_team_seasons_team_season_id', 'competitions', type_='foreignkey')
    op.create_foreign_key('fk_team_seasons_team_season_id', 'competitions', 'team_seasons', ['team_season_id'], ['team_season_id'])
    op.drop_constraint('fk_competitions_competition_id', 'matches', type_='foreignkey')
    op.create_foreign_key('fk_competitions_competition_id', 'matches', 'competitions', ['competition_id'], ['competition_id'])
    op.drop_constraint('fk_data_sources_data_source_id', 'metrics', type_='foreignkey')
    op.create_foreign_key('fk_data_sources_data_source_id', 'metrics', 'data_sources', ['data_source_id'], ['data_source_id'])
    op.drop_constraint('fk_metrics_metric_id', 'player_match_performances', type_='foreignkey')
    op.drop_constraint('fk_players_player_id', 'player_match_performances', type_='foreignkey')
    op.drop_constraint('fk_matches_match_id', 'player_match_performances', type_='foreignkey')
    op.create_foreign_key('fk_metrics_metric_id', 'player_match_performances', 'metrics', ['metric_id'], ['metric_id'])
    op.create_foreign_key('fk_matches_match_id', 'player_match_performances', 'matches', ['match_id'], ['match_id'])
    op.create_foreign_key('fk_players_player_id', 'player_match_performances', 'players', ['player_id'], ['player_id'])
    op.drop_constraint('fk_clubs_club_id', 'players', type_='foreignkey')
    op.create_foreign_key('fk_clubs_club_id', 'players', 'clubs', ['club_id'], ['club_id'])
    op.drop_constraint('fk_seasons_season_id', 'team_seasons', type_='foreignkey')
    op.drop_constraint('fk_data_sources_data_source_id', 'team_seasons', type_='foreignkey')
    op.drop_constraint('fk_teams_team_id', 'team_seasons', type_='foreignkey')
    op.create_foreign_key('fk_teams_team_id', 'team_seasons', 'teams', ['team_id'], ['team_id'])
    op.create_foreign_key('fk_data_sources_data_source_id', 'team_seasons', 'data_sources', ['data_source_id'], ['data_source_id'])
    op.create_foreign_key('fk_seasons_season_id', 'team_seasons', 'seasons', ['season_id'], ['season_id'])
    op.drop_constraint('fk_sports_sport_id', 'teams', type_='foreignkey')
    op.drop_constraint('fk_clubs_club_id', 'teams', type_='foreignkey')
    op.create_foreign_key('fk_sports_sport_id', 'teams', 'sports', ['sport_id'], ['sport_id'])
    op.create_foreign_key('fk_clubs_club_id', 'teams', 'clubs', ['club_id'], ['club_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_clubs_club_id', 'teams', type_='foreignkey')
    op.drop_constraint('fk_sports_sport_id', 'teams', type_='foreignkey')
    op.create_foreign_key('fk_clubs_club_id', 'teams', 'clubs', ['club_id'], ['club_id'], referent_schema='squad_stats')
    op.create_foreign_key('fk_sports_sport_id', 'teams', 'sports', ['sport_id'], ['sport_id'], referent_schema='squad_stats')
    op.drop_constraint('fk_seasons_season_id', 'team_seasons', type_='foreignkey')
    op.drop_constraint('fk_data_sources_data_source_id', 'team_seasons', type_='foreignkey')
    op.drop_constraint('fk_teams_team_id', 'team_seasons', type_='foreignkey')
    op.create_foreign_key('fk_teams_team_id', 'team_seasons', 'teams', ['team_id'], ['team_id'], referent_schema='squad_stats')
    op.create_foreign_key('fk_data_sources_data_source_id', 'team_seasons', 'data_sources', ['data_source_id'], ['data_source_id'], referent_schema='squad_stats')
    op.create_foreign_key('fk_seasons_season_id', 'team_seasons', 'seasons', ['season_id'], ['season_id'], referent_schema='squad_stats')
    op.drop_constraint('fk_clubs_club_id', 'players', type_='foreignkey')
    op.create_foreign_key('fk_clubs_club_id', 'players', 'clubs', ['club_id'], ['club_id'], referent_schema='squad_stats')
    op.drop_constraint('fk_players_player_id', 'player_match_performances', type_='foreignkey')
    op.drop_constraint('fk_matches_match_id', 'player_match_performances', type_='foreignkey')
    op.drop_constraint('fk_metrics_metric_id', 'player_match_performances', type_='foreignkey')
    op.create_foreign_key('fk_matches_match_id', 'player_match_performances', 'matches', ['match_id'], ['match_id'], referent_schema='squad_stats')
    op.create_foreign_key('fk_players_player_id', 'player_match_performances', 'players', ['player_id'], ['player_id'], referent_schema='squad_stats')
    op.create_foreign_key('fk_metrics_metric_id', 'player_match_performances', 'metrics', ['metric_id'], ['metric_id'], referent_schema='squad_stats')
    op.drop_constraint('fk_data_sources_data_source_id', 'metrics', type_='foreignkey')
    op.create_foreign_key('fk_data_sources_data_source_id', 'metrics', 'data_sources', ['data_source_id'], ['data_source_id'], referent_schema='squad_stats')
    op.drop_constraint('fk_competitions_competition_id', 'matches', type_='foreignkey')
    op.create_foreign_key('fk_competitions_competition_id', 'matches', 'competitions', ['competition_id'], ['competition_id'], referent_schema='squad_stats')
    op.drop_constraint('fk_team_seasons_team_season_id', 'competitions', type_='foreignkey')
    op.create_foreign_key('fk_team_seasons_team_season_id', 'competitions', 'team_seasons', ['team_season_id'], ['team_season_id'], referent_schema='squad_stats')
    op.drop_constraint('fk_clubs_club_id', 'club_admins', type_='foreignkey')
    op.drop_constraint('fk_users_user_id', 'club_admins', type_='foreignkey')
    op.create_foreign_key('fk_users_user_id', 'club_admins', 'users', ['user_id'], ['user_id'], referent_schema='squad_stats')
    op.create_foreign_key('fk_clubs_club_id', 'club_admins', 'clubs', ['club_id'], ['club_id'], referent_schema='squad_stats')
    # ### end Alembic commands ###
