name: Deploy to Fly.io

on:
  push:
    branches:
      - main  # or your deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure mise to compile Python from source
        run: mise settings set python_compile 1

      - name: Set up Python with mise
        run: mise use -g python@3.12

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Deploy to Fly
        uses: superfly/flyctl-actions@1.3
        with:
          args: deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}