name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install mise
        uses: jdx/mise-action@v2

      - name: Force mise to compile Python from source
        run: mise settings set python_compile 1

      - name: Install Python 3.12 using mise (compiled)
        run: mise use -g python@3.12

      - name: Install pip dependencies
        run: pip install -r requirements.txt

      - name: Deploy to Fly
        uses: superfly/flyctl-actions@1.3
        with:
          args: deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}