"""initital commit again

Revision ID: 6fdb82a4eb62
Revises: 
Create Date: 2024-10-24 23:22:04.025137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fdb82a4eb62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('club_id', sa.Uuid(), nullable=False),
    sa.Column('club_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('club_id')
    )
    op.create_table('data_sources',
    sa.Column('data_source_id', sa.Uuid(), nullable=False),
    sa.Column('data_source_name', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('data_source_id')
    )
    op.create_table('seasons',
    sa.Column('season_id', sa.Uuid(), nullable=False),
    sa.Column('season_name', sa.String(length=50), nullable=False),
    sa.Column('data_source_season_id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('season_id')
    )
    op.create_table('sports',
    sa.Column('sport_id', sa.Uuid(), nullable=False),
    sa.Column('sport_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('sport_id')
    )
    op.create_table('team_names',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('team_name', sa.String(length=50), nullable=False),
    sa.Column('is_default_name', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('metrics',
    sa.Column('metric_id', sa.Uuid(), nullable=False),
    sa.Column('data_source_id', sa.Uuid(), nullable=False),
    sa.Column('metric_name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.data_source_id'], name='fk_data_sources_data_source_id'),
    sa.PrimaryKeyConstraint('metric_id')
    )
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metrics_data_source_id'), ['data_source_id'], unique=False)

    op.create_table('players',
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('club_id', sa.Uuid(), nullable=False),
    sa.Column('data_source_player_name', sa.String(length=100), nullable=False),
    sa.Column('better_player_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.club_id'], name='fk_clubs_club_id'),
    sa.PrimaryKeyConstraint('player_id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_club_id'), ['club_id'], unique=False)

    op.create_table('teams',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('club_id', sa.Uuid(), nullable=False),
    sa.Column('sport_id', sa.Uuid(), nullable=False),
    sa.Column('data_source_team_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.club_id'], name='fk_clubs_club_id'),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.sport_id'], name='fk_sports_sport_id'),
    sa.PrimaryKeyConstraint('team_id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_club_id'), ['club_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_sport_id'), ['sport_id'], unique=False)

    op.create_table('team_seasons',
    sa.Column('team_season_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('season_id', sa.Uuid(), nullable=False),
    sa.Column('data_source_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.data_source_id'], name='fk_data_sources_data_source_id'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], name='fk_seasons_season_id'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], name='fk_teams_team_id'),
    sa.PrimaryKeyConstraint('team_season_id')
    )
    with op.batch_alter_table('team_seasons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_seasons_data_source_id'), ['data_source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_seasons_season_id'), ['season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_seasons_team_id'), ['team_id'], unique=False)

    op.create_table('competitions',
    sa.Column('competition_id', sa.Uuid(), nullable=False),
    sa.Column('data_source_competition_id', sa.String(length=100), nullable=False),
    sa.Column('competition_name', sa.String(length=100), nullable=False),
    sa.Column('team_season_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['team_season_id'], ['team_seasons.team_season_id'], name='fk_team_seasons_team_season_id'),
    sa.PrimaryKeyConstraint('competition_id')
    )
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitions_team_season_id'), ['team_season_id'], unique=False)

    op.create_table('matches',
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('competition_id', sa.Uuid(), nullable=False),
    sa.Column('goals_for', sa.Integer(), nullable=False),
    sa.Column('goals_against', sa.Integer(), nullable=False),
    sa.Column('goal_difference', sa.Integer(), nullable=False),
    sa.Column('opposition_team_name', sa.String(length=100), nullable=False),
    sa.Column('result', sa.String(length=1), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('home_away_neutral', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.competition_id'], name='fk_competitions_competition_id'),
    sa.PrimaryKeyConstraint('match_id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_competition_id'), ['competition_id'], unique=False)

    op.create_table('player_match_performances',
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('metric_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], name='fk_matches_match_id'),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.metric_id'], name='fk_metrics_metric_id'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], name='fk_players_player_id'),
    sa.PrimaryKeyConstraint('player_id', 'match_id', 'metric_id')
    )
    with op.batch_alter_table('player_match_performances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_match_performances_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_match_performances_metric_id'), ['metric_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_match_performances_player_id'), ['player_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_match_performances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_match_performances_player_id'))
        batch_op.drop_index(batch_op.f('ix_player_match_performances_metric_id'))
        batch_op.drop_index(batch_op.f('ix_player_match_performances_match_id'))

    op.drop_table('player_match_performances')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_competition_id'))

    op.drop_table('matches')
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitions_team_season_id'))

    op.drop_table('competitions')
    with op.batch_alter_table('team_seasons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_seasons_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_seasons_season_id'))
        batch_op.drop_index(batch_op.f('ix_team_seasons_data_source_id'))

    op.drop_table('team_seasons')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_sport_id'))
        batch_op.drop_index(batch_op.f('ix_teams_club_id'))

    op.drop_table('teams')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_club_id'))

    op.drop_table('players')
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metrics_data_source_id'))

    op.drop_table('metrics')
    op.drop_table('team_names')
    op.drop_table('sports')
    op.drop_table('seasons')
    op.drop_table('data_sources')
    op.drop_table('clubs')
    # ### end Alembic commands ###
