"""make password col longer and added time created to club

Revision ID: 7f139bb6e6f0
Revises: f1e78ca81ee6
Create Date: 2024-10-25 23:13:22.764837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f139bb6e6f0'
down_revision = 'f1e78ca81ee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_created', sa.DateTime(), nullable=False))

    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_team_seasons_team_season_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_team_seasons_team_season_id', 'team_seasons', ['team_season_id'], ['team_season_id'])

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint('fk_competitions_competition_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_competitions_competition_id', 'competitions', ['competition_id'], ['competition_id'])

    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.drop_constraint('fk_data_sources_data_source_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_data_sources_data_source_id', 'data_sources', ['data_source_id'], ['data_source_id'])

    with op.batch_alter_table('player_match_performances', schema=None) as batch_op:
        batch_op.drop_constraint('fk_matches_match_id', type_='foreignkey')
        batch_op.drop_constraint('fk_players_player_id', type_='foreignkey')
        batch_op.drop_constraint('fk_metrics_metric_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_matches_match_id', 'matches', ['match_id'], ['match_id'])
        batch_op.create_foreign_key('fk_metrics_metric_id', 'metrics', ['metric_id'], ['metric_id'])
        batch_op.create_foreign_key('fk_players_player_id', 'players', ['player_id'], ['player_id'])

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint('fk_clubs_club_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_clubs_club_id', 'clubs', ['club_id'], ['club_id'])

    with op.batch_alter_table('team_seasons', schema=None) as batch_op:
        batch_op.drop_constraint('fk_data_sources_data_source_id', type_='foreignkey')
        batch_op.drop_constraint('fk_teams_team_id', type_='foreignkey')
        batch_op.drop_constraint('fk_seasons_season_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_teams_team_id', 'teams', ['team_id'], ['team_id'])
        batch_op.create_foreign_key('fk_data_sources_data_source_id', 'data_sources', ['data_source_id'], ['data_source_id'])
        batch_op.create_foreign_key('fk_seasons_season_id', 'seasons', ['season_id'], ['season_id'])

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sports_sport_id', type_='foreignkey')
        batch_op.drop_constraint('fk_clubs_club_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_clubs_club_id', 'clubs', ['club_id'], ['club_id'])
        batch_op.create_foreign_key('fk_sports_sport_id', 'sports', ['sport_id'], ['sport_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=130),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=130),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sports_sport_id', type_='foreignkey')
        batch_op.drop_constraint('fk_clubs_club_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_clubs_club_id', 'clubs', ['club_id'], ['club_id'], referent_schema='squad_stats')
        batch_op.create_foreign_key('fk_sports_sport_id', 'sports', ['sport_id'], ['sport_id'], referent_schema='squad_stats')

    with op.batch_alter_table('team_seasons', schema=None) as batch_op:
        batch_op.drop_constraint('fk_seasons_season_id', type_='foreignkey')
        batch_op.drop_constraint('fk_data_sources_data_source_id', type_='foreignkey')
        batch_op.drop_constraint('fk_teams_team_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_seasons_season_id', 'seasons', ['season_id'], ['season_id'], referent_schema='squad_stats')
        batch_op.create_foreign_key('fk_teams_team_id', 'teams', ['team_id'], ['team_id'], referent_schema='squad_stats')
        batch_op.create_foreign_key('fk_data_sources_data_source_id', 'data_sources', ['data_source_id'], ['data_source_id'], referent_schema='squad_stats')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint('fk_clubs_club_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_clubs_club_id', 'clubs', ['club_id'], ['club_id'], referent_schema='squad_stats')

    with op.batch_alter_table('player_match_performances', schema=None) as batch_op:
        batch_op.drop_constraint('fk_players_player_id', type_='foreignkey')
        batch_op.drop_constraint('fk_metrics_metric_id', type_='foreignkey')
        batch_op.drop_constraint('fk_matches_match_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_metrics_metric_id', 'metrics', ['metric_id'], ['metric_id'], referent_schema='squad_stats')
        batch_op.create_foreign_key('fk_players_player_id', 'players', ['player_id'], ['player_id'], referent_schema='squad_stats')
        batch_op.create_foreign_key('fk_matches_match_id', 'matches', ['match_id'], ['match_id'], referent_schema='squad_stats')

    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.drop_constraint('fk_data_sources_data_source_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_data_sources_data_source_id', 'data_sources', ['data_source_id'], ['data_source_id'], referent_schema='squad_stats')

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint('fk_competitions_competition_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_competitions_competition_id', 'competitions', ['competition_id'], ['competition_id'], referent_schema='squad_stats')

    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_team_seasons_team_season_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_team_seasons_team_season_id', 'team_seasons', ['team_season_id'], ['team_season_id'], referent_schema='squad_stats')

    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_column('time_created')

    # ### end Alembic commands ###
