"""added datetime col to abrordob_markers

Revision ID: 8d17b1c6533d
Revises: fb8c9005c0d6
Create Date: 2024-10-19 17:42:27.601433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d17b1c6533d'
down_revision = 'fb8c9005c0d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abrordob_markers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_time', sa.DateTime(), nullable=False))

    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'team_seasons', ['team_season_id'], ['team_season_id'])

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint('fk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'competitions', ['competition_id'], ['competition_id'])

    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.drop_constraint('fk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'data_sources', ['data_source_id'], ['data_source_id'])

    with op.batch_alter_table('player_match_performances', schema=None) as batch_op:
        batch_op.drop_constraint('fk_2', type_='foreignkey')
        batch_op.drop_constraint('fk_3', type_='foreignkey')
        batch_op.drop_constraint('fk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'players', ['player_id'], ['player_id'])
        batch_op.create_foreign_key(None, 'metrics', ['metric_id'], ['metric_id'])
        batch_op.create_foreign_key(None, 'matches', ['match_id'], ['match_id'])

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint('fk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'clubs', ['club_id'], ['club_id'])

    with op.batch_alter_table('team_seasons', schema=None) as batch_op:
        batch_op.drop_constraint('fk_1', type_='foreignkey')
        batch_op.drop_constraint('fk_2', type_='foreignkey')
        batch_op.drop_constraint('fk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'data_sources', ['data_source_id'], ['data_source_id'])
        batch_op.create_foreign_key(None, 'teams', ['team_id'], ['team_id'])
        batch_op.create_foreign_key(None, 'seasons', ['season_id'], ['season_id'])

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint('fk_2', type_='foreignkey')
        batch_op.drop_constraint('fk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'sports', ['sport_id'], ['sport_id'])
        batch_op.create_foreign_key(None, 'clubs', ['club_id'], ['club_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_1', 'clubs', ['club_id'], ['club_id'], referent_schema='squad_stats')
        batch_op.create_foreign_key('fk_2', 'sports', ['sport_id'], ['sport_id'], referent_schema='squad_stats')

    with op.batch_alter_table('team_seasons', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_3', 'teams', ['team_id'], ['team_id'], referent_schema='squad_stats')
        batch_op.create_foreign_key('fk_2', 'seasons', ['season_id'], ['season_id'], referent_schema='squad_stats')
        batch_op.create_foreign_key('fk_1', 'data_sources', ['data_source_id'], ['data_source_id'], referent_schema='squad_stats')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_1', 'clubs', ['club_id'], ['club_id'], referent_schema='squad_stats')

    with op.batch_alter_table('player_match_performances', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_1', 'matches', ['match_id'], ['match_id'], referent_schema='squad_stats')
        batch_op.create_foreign_key('fk_3', 'players', ['player_id'], ['player_id'], referent_schema='squad_stats')
        batch_op.create_foreign_key('fk_2', 'metrics', ['metric_id'], ['metric_id'], referent_schema='squad_stats')

    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_1', 'data_sources', ['data_source_id'], ['data_source_id'], referent_schema='squad_stats')

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_1', 'competitions', ['competition_id'], ['competition_id'], referent_schema='squad_stats')

    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_1', 'team_seasons', ['team_season_id'], ['team_season_id'], referent_schema='squad_stats')

    with op.batch_alter_table('abrordob_markers', schema=None) as batch_op:
        batch_op.drop_column('date_time')

    # ### end Alembic commands ###
