"""add club_admins

Revision ID: f00246d7a822
Revises: 409620b27488
Create Date: 2024-11-03 16:12:39.145246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f00246d7a822'
down_revision = '409620b27488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_admins',
    sa.Column('club_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('better_player_name', sa.String(length=100), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.club_id'], name='fk_clubs_club_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='fk_users_user_id'),
    sa.PrimaryKeyConstraint('club_id', 'user_id')
    )
    with op.batch_alter_table('club_admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_club_admins_club_id'), ['club_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_club_admins_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_team_seasons_team_season_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_team_seasons_team_season_id', 'team_seasons', ['team_season_id'], ['team_season_id'])

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint('fk_competitions_competition_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_competitions_competition_id', 'competitions', ['competition_id'], ['competition_id'])

    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.drop_constraint('fk_data_sources_data_source_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_data_sources_data_source_id', 'data_sources', ['data_source_id'], ['data_source_id'])

    with op.batch_alter_table('player_match_performances', schema=None) as batch_op:
        batch_op.drop_constraint('fk_metrics_metric_id', type_='foreignkey')
        batch_op.drop_constraint('fk_matches_match_id', type_='foreignkey')
        batch_op.drop_constraint('fk_players_player_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_metrics_metric_id', 'metrics', ['metric_id'], ['metric_id'])
        batch_op.create_foreign_key('fk_matches_match_id', 'matches', ['match_id'], ['match_id'])
        batch_op.create_foreign_key('fk_players_player_id', 'players', ['player_id'], ['player_id'])

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint('fk_clubs_club_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_clubs_club_id', 'clubs', ['club_id'], ['club_id'])

    with op.batch_alter_table('team_seasons', schema=None) as batch_op:
        batch_op.drop_constraint('fk_seasons_season_id', type_='foreignkey')
        batch_op.drop_constraint('fk_teams_team_id', type_='foreignkey')
        batch_op.drop_constraint('fk_data_sources_data_source_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_data_sources_data_source_id', 'data_sources', ['data_source_id'], ['data_source_id'])
        batch_op.create_foreign_key('fk_seasons_season_id', 'seasons', ['season_id'], ['season_id'])
        batch_op.create_foreign_key('fk_teams_team_id', 'teams', ['team_id'], ['team_id'])

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sports_sport_id', type_='foreignkey')
        batch_op.drop_constraint('fk_clubs_club_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_clubs_club_id', 'clubs', ['club_id'], ['club_id'])
        batch_op.create_foreign_key('fk_sports_sport_id', 'sports', ['sport_id'], ['sport_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sports_sport_id', type_='foreignkey')
        batch_op.drop_constraint('fk_clubs_club_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_clubs_club_id', 'clubs', ['club_id'], ['club_id'], referent_schema='squad_stats')
        batch_op.create_foreign_key('fk_sports_sport_id', 'sports', ['sport_id'], ['sport_id'], referent_schema='squad_stats')

    with op.batch_alter_table('team_seasons', schema=None) as batch_op:
        batch_op.drop_constraint('fk_teams_team_id', type_='foreignkey')
        batch_op.drop_constraint('fk_seasons_season_id', type_='foreignkey')
        batch_op.drop_constraint('fk_data_sources_data_source_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_data_sources_data_source_id', 'data_sources', ['data_source_id'], ['data_source_id'], referent_schema='squad_stats')
        batch_op.create_foreign_key('fk_teams_team_id', 'teams', ['team_id'], ['team_id'], referent_schema='squad_stats')
        batch_op.create_foreign_key('fk_seasons_season_id', 'seasons', ['season_id'], ['season_id'], referent_schema='squad_stats')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint('fk_clubs_club_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_clubs_club_id', 'clubs', ['club_id'], ['club_id'], referent_schema='squad_stats')

    with op.batch_alter_table('player_match_performances', schema=None) as batch_op:
        batch_op.drop_constraint('fk_players_player_id', type_='foreignkey')
        batch_op.drop_constraint('fk_matches_match_id', type_='foreignkey')
        batch_op.drop_constraint('fk_metrics_metric_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_players_player_id', 'players', ['player_id'], ['player_id'], referent_schema='squad_stats')
        batch_op.create_foreign_key('fk_matches_match_id', 'matches', ['match_id'], ['match_id'], referent_schema='squad_stats')
        batch_op.create_foreign_key('fk_metrics_metric_id', 'metrics', ['metric_id'], ['metric_id'], referent_schema='squad_stats')

    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.drop_constraint('fk_data_sources_data_source_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_data_sources_data_source_id', 'data_sources', ['data_source_id'], ['data_source_id'], referent_schema='squad_stats')

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint('fk_competitions_competition_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_competitions_competition_id', 'competitions', ['competition_id'], ['competition_id'], referent_schema='squad_stats')

    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_team_seasons_team_season_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_team_seasons_team_season_id', 'team_seasons', ['team_season_id'], ['team_season_id'], referent_schema='squad_stats')

    with op.batch_alter_table('club_admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_club_admins_user_id'))
        batch_op.drop_index(batch_op.f('ix_club_admins_club_id'))

    op.drop_table('club_admins')
    # ### end Alembic commands ###
