"""initial commit

Revision ID: fb8c9005c0d6
Revises: 
Create Date: 2024-10-19 14:15:04.637653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb8c9005c0d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abrordob_markers',
    sa.Column('marker_id', sa.String(length=20), nullable=False),
    sa.Column('colour', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('text', sa.String(length=16383), nullable=False),
    sa.PrimaryKeyConstraint('marker_id')
    )
    op.create_table('clubs',
    sa.Column('club_id', sa.Uuid(), nullable=False),
    sa.Column('club_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('club_id')
    )
    op.create_table('data_sources',
    sa.Column('data_source_id', sa.Uuid(), nullable=False),
    sa.Column('data_source_name', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('data_source_id')
    )
    op.create_table('seasons',
    sa.Column('season_id', sa.Uuid(), nullable=False),
    sa.Column('season_name', sa.String(length=50), nullable=False),
    sa.Column('data_source_season_id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('season_id')
    )
    op.create_table('sports',
    sa.Column('sport_id', sa.Uuid(), nullable=False),
    sa.Column('sport_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('sport_id')
    )
    op.create_table('team_names',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('team_name', sa.String(length=50), nullable=False),
    sa.Column('is_default_name', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('metrics',
    sa.Column('metric_id', sa.Uuid(), nullable=False),
    sa.Column('data_source_id', sa.Uuid(), nullable=False),
    sa.Column('metric_name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.data_source_id'], ),
    sa.PrimaryKeyConstraint('metric_id')
    )
    op.create_table('players',
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('club_id', sa.Uuid(), nullable=False),
    sa.Column('data_source_player_name', sa.String(length=100), nullable=False),
    sa.Column('better_player_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.club_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('club_id', sa.Uuid(), nullable=False),
    sa.Column('sport_id', sa.Uuid(), nullable=False),
    sa.Column('data_source_team_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.club_id'], ),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.sport_id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('team_seasons',
    sa.Column('team_season_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('season_id', sa.Uuid(), nullable=False),
    sa.Column('data_source_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.data_source_id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('team_season_id')
    )
    op.create_table('competitions',
    sa.Column('competition_id', sa.Uuid(), nullable=False),
    sa.Column('data_source_competition_id', sa.String(length=100), nullable=False),
    sa.Column('competition_name', sa.String(length=100), nullable=False),
    sa.Column('team_season_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['team_season_id'], ['team_seasons.team_season_id'], ),
    sa.PrimaryKeyConstraint('competition_id')
    )
    op.create_table('matches',
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('competition_id', sa.Uuid(), nullable=False),
    sa.Column('goals_for', sa.Integer(), nullable=False),
    sa.Column('goals_against', sa.Integer(), nullable=False),
    sa.Column('goal_difference', sa.Integer(), nullable=False),
    sa.Column('opposition_team_name', sa.String(length=100), nullable=False),
    sa.Column('result', sa.String(length=1), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('home_away_neutral', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.competition_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('player_match_performances',
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('metric_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.metric_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('player_id', 'match_id', 'metric_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_match_performances')
    op.drop_table('matches')
    op.drop_table('competitions')
    op.drop_table('team_seasons')
    op.drop_table('teams')
    op.drop_table('players')
    op.drop_table('metrics')
    op.drop_table('team_names')
    op.drop_table('sports')
    op.drop_table('seasons')
    op.drop_table('data_sources')
    op.drop_table('clubs')
    op.drop_table('abrordob_markers')
    # ### end Alembic commands ###
